import { TrackedMutation } from '../fixtures/data-tracker.fixture';

/**
 * Generate rollback SQL statements from tracked data mutations.
 *
 * Table: `trs_masking` (confirmed from admin-service repository)
 * Columns: id, tenant_id, txtp, txtp_version, tokenize, status,
 *          fields_masked, total_fields, comments, created_at, updated_at
 *
 * THE FRAMEWORK NEVER EXECUTES ANY SQL. SQL IS DISPLAY-ONLY.
 */

const MASKING_TABLE = 'trs_masking';

export interface RollbackStatement {
  sql: string;
  comment: string;
  mutation: TrackedMutation;
}

function escapeSQL(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'object') return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  return `'${String(value).replace(/'/g, "''")}'`;
}

function extractResourceId(mutation: TrackedMutation): string | null {
  // Try response body first
  const body = mutation.responseBody as Record<string, unknown> | null;
  if (body?.id) return String(body.id);
  if ((body as any)?.data?.id) return String((body as any).data.id);
  // Try from endpoint path
  const match = mutation.endpoint.match(/\/(\d+)(?:\/|$)/);
  if (match) return match[1];
  return null;
}

function generateDeleteSQL(mutation: TrackedMutation): RollbackStatement | null {
  const id = extractResourceId(mutation);
  if (!id) return null;

  return {
    sql: `DELETE FROM ${MASKING_TABLE} WHERE id = ${escapeSQL(id)};`,
    comment: `Rollback CREATE: Remove masking config created by test "${mutation.testName}" (user: ${mutation.userRole}) at ${mutation.timestamp}`,
    mutation,
  };
}

function generateUpdateSQL(mutation: TrackedMutation): RollbackStatement | null {
  if (!mutation.beforeState) return null;

  const id = extractResourceId(mutation);
  if (!id) return null;

  const setClauses: string[] = [];
  const before = mutation.beforeState;

  for (const [key, value] of Object.entries(before)) {
    if (key === 'id' || key === 'created_at') continue;
    setClauses.push(`${key} = ${escapeSQL(value)}`);
  }

  if (setClauses.length === 0) return null;

  return {
    sql: `UPDATE ${MASKING_TABLE} SET ${setClauses.join(', ')} WHERE id = ${escapeSQL(id)};`,
    comment: `Rollback UPDATE: Restore masking config to state before test "${mutation.testName}" (user: ${mutation.userRole}) at ${mutation.timestamp}`,
    mutation,
  };
}

export function generateRollbackSQL(mutations: TrackedMutation[]): RollbackStatement[] {
  const statements: RollbackStatement[] = [];

  // Process in reverse chronological order (undo newest first)
  const sorted = [...mutations].sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime(),
  );

  for (const mutation of sorted) {
    let statement: RollbackStatement | null = null;

    switch (mutation.method) {
      case 'POST':
        statement = generateDeleteSQL(mutation);
        break;
      case 'PUT':
      case 'PATCH':
        statement = generateUpdateSQL(mutation);
        break;
      case 'DELETE':
        // Can't easily reverse a delete without full row data
        statements.push({
          sql: `-- WARNING: Cannot auto-generate INSERT for deleted resource. Manual restoration needed.`,
          comment: `Rollback DELETE: Resource deleted by test "${mutation.testName}" at ${mutation.timestamp}`,
          mutation,
        });
        continue;
    }

    if (statement) {
      statements.push(statement);
    }
  }

  return statements;
}

export function formatRollbackSQL(statements: RollbackStatement[]): string {
  const lines: string[] = [
    '-- ============================================',
    '-- ROLLBACK SQL — AUTO-GENERATED BY TEST FRAMEWORK',
    '-- WARNING: Review carefully before executing!',
    '-- THE TEST FRAMEWORK NEVER EXECUTES THIS SQL.',
    '-- ============================================',
    '',
  ];

  for (const stmt of statements) {
    lines.push(`-- ${stmt.comment}`);
    lines.push(stmt.sql);
    lines.push('');
  }

  return lines.join('\n');
}
